apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-detectar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-detectar
  template:
    metadata:
      labels:
        app: flask-detectar
    spec:
      containers:
        - name: flask-app-detectar
          image: andmas199/pti:flask-detectar
          ports:
            - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service-detectar
spec:
  type: NodePort
  selector:
    app: flask-detectar
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
