apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-vectores
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-vectores
  template:
    metadata:
      labels:
        app: flask-vectores
    spec:
      containers:
        - name: flask-app-vectores
          image: andmas199/pti:flask-vectores  
          ports:
            - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service-vectores
spec:
  type: NodePort
  selector:
    app: flask-vectores
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
